### ISSUE TITLE
BUG: jsdom 版本过低

### ISSUE THREAD

**Issue by zzmark** [easyyapi/yapi-markdown-render#1]
环境版本：
```
node: v14.17.0 LTS
```

直接初始化会发生下面错误

```
> yapi-markdown-render@1.0.0 start /usr/src/app
>  node app.js "3000"

/usr/src/app/node_modules/whatwg-url/dist/URL.js:84
  if (!globalNames.some(globalName => exposed.has(globalName))) {
                   ^

TypeError: Cannot read property 'some' of undefined
    at Object.exports.install (/usr/src/app/node_modules/whatwg-url/dist/URL.js:84:20)
    at exports.installInterfaces (/usr/src/app/node_modules/jsdom/lib/jsdom/living/interfaces.js:201:24)
    at setupWindow (/usr/src/app/node_modules/jsdom/lib/jsdom/browser/Window.js:63:3)
    at new Window (/usr/src/app/node_modules/jsdom/lib/jsdom/browser/Window.js:107:3)
    at exports.createWindow (/usr/src/app/node_modules/jsdom/lib/jsdom/browser/Window.js:38:10)
    at new JSDOM (/usr/src/app/node_modules/jsdom/lib/api.js:36:20)
    at Object.<anonymous> (/usr/src/app/render-core.js:13:13)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yapi-markdown-render@1.0.0 start: ` node app.js "3000"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the yapi-markdown-render@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-02T08_57_44_110Z-debug.log
```

问题原因在 https://github.com/jsdom/whatwg-url/issues/166#issuecomment-685678185 有报告问题，升级依赖即可解决

```diff
-  "jsdom": "16.2.0", 
+  "jsdom": "16.6.0",
```

**Comment by tangcent** [comment]
I got it.
Um...feel free to fix it and make a pull request. I’ll be happy to pull it.

**Comment by zzmark** [comment]
ok. i will do it later
